# Generated by Django 5.2 on 2025-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('bouake', 'Bouaké'), ('daloa', 'Daloa'), ('yamoussoukro', 'Yamoussoukro'), ('sanpedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('man', 'Man'), ('other', 'Autre ville')], default='abidjan', max_length=100, null=True, verbose_name='ville'),
        ),
    ]
