# Generated by Django 5.2 on 2025-09-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('min_match_score', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_vector', models.JSONField(blank=True, default=list)),
                ('interests_vector', models.JSONField(blank=True, default=list)),
                ('career_goals', models.TextField(blank=True)),
                ('preference_score', models.JSONField(blank=True, default=dict)),
                ('applied_opportunities', models.ManyToManyField(blank=True, related_name='applied_by_users', to='opportunities.opportunity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
                ('viewed_opportunities', models.ManyToManyField(blank=True, related_name='viewed_by_users', to='opportunities.opportunity')),
            ],
        ),
    ]
